JobProcess/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),

    path('', include('main.urls'))
]

main/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import MainView, UpdateWorkView, CreateWorkView, delete_work, DetailIssueView, CreateIssueView, \
    UpdateIssueView, SearchView, SearchNoConView, delete_issue

search_patterns = [
    path('manager/<manager>/status/<status>/contents/<contents>', SearchView.as_view(), name='search'),
    path('manager/<manager>/status/<status>/contents/', SearchNoConView.as_view(), name='search'),
    # path('manager/<query>', SearchManView.as_view()),
    # path('status/<query>', SearchStatusView.as_view()),
]

urlpatterns = [
    path('', MainView.as_view(), name='index'),
    path('search/', include(search_patterns)),
    path('issueDetail/<int:pk>', DetailIssueView.as_view()),
    path('update/<int:pk>', UpdateWorkView.as_view()),
    path('issueUpdate/<int:pk>', UpdateIssueView.as_view()),
    path('create/', CreateWorkView.as_view()),
    path('issueCreate/<int:work>', CreateIssueView.as_view()),
    path('issueCreate/', CreateIssueView.as_view()),
    path('delete/<int:id>', delete_work),
    path('issue/delete/<int:id>', delete_issue),
]

main/models.py
from datetime import datetime

from django.contrib.auth.models import AbstractUser
from django.db import models


class Employee(models.Model):
    name = models.CharField(max_length=10)

    def __str__(self):
        return self.name


class MyUser(AbstractUser):
    name = models.CharField(max_length=20)

    def __str__(self):
        return self.name


class WorkStatus(models.Model):
    title = models.CharField(max_length=10)
    value = models.CharField(max_length=10)

    def __str__(self):
        return self.title


class IssueStatus(models.Model):
    title = models.CharField(max_length=10)
    value = models.CharField(max_length=10)

    def __str__(self):
        return self.title


class Work(models.Model):
    manager = models.ForeignKey(MyUser, on_delete=models.SET_NULL, related_name='manager', null=True)
    supporter = models.ManyToManyField(MyUser, blank=True)
    work = models.TextField()
    status = models.ForeignKey(WorkStatus, on_delete=models.SET_NULL, related_name='status', null=True)
    start_date = models.DateField(default=datetime.now, null=True)
    expected_end_date = models.DateField(null=True)
    end_date = models.DateField(null=True)

    def __str__(self):
        return "%s: %s" % (self.manager, self.work)


class Issue(models.Model):
    work = models.ForeignKey(Work, on_delete=models.CASCADE)
    start_date = models.DateField(default=datetime.now)
    end_date = models.DateField(null=True)
    content = models.TextField(null=True)
    status = models.ForeignKey(IssueStatus, on_delete=models.SET_NULL, related_name='status', null=True)
    replay = models.TextField(null=True)
    cause = models.TextField(null=True)
    solution = models.TextField(null=True)

main/forms.py
from django import forms
from .models import Work, Issue, WorkStatus, IssueStatus, Employee


# class WorkForm(forms.Form):
#     manager = forms.CharField(label="담당자명", max_length=10)
#     supporter = forms.CharField(label="업무협조", max_length=10)
#     work = forms.CharField(label="업무 내용", widget=forms.Textarea)
#     status = forms.CharField(label="업무 상태", max_length=10)
#     start_date = forms.DateField(label="시작일")
#     expected_end_date = forms.DateField(label="종료 예정일")
#     end_date = forms.DateField(label="종료일")


class WorkForm(forms.ModelForm):
    # end_date = forms.DateField(label="종료일", required=False)
    def __init__(self, *args, **kwargs):
        # first call parent's constructor
        super(WorkForm, self).__init__(*args, **kwargs)
        # there's a `fields` property now
        self.fields['end_date'].required = False
        self.fields['start_date'].required = False
        self.fields['expected_end_date'].required = True

    class Meta:
        model = Work
        fields = '__all__'

        # status_CHOICE = tuple(WorkStatus.objects.all())
        # print(tuple(WorkStatus.objects.))

        widgets = {
            'manager': forms.Select(attrs={'class': 'form-control col-md-2'}),
            'supporter': forms.CheckboxSelectMultiple(attrs={'class': 'form-check-input'}),
            'work': forms.Textarea(attrs={'class': 'form-control'}),
            'status': forms.Select(attrs={'class': 'form-control col-md-2'}),
            'start_date': forms.DateInput(attrs={'class': 'form-control col-md-3', 'id':'datepicker1'}),
            'expected_end_date': forms.DateInput(attrs={'class': 'form-control col-md-3', 'id':'datepicker2'}),
            'end_date': forms.DateInput(attrs={'class': 'form-control col-md-3', 'id':'datepicker3'}),
        }
        labels = {
            'manager': '담당자',
            'supporter': '업무 협조',
            'work': "업무 내용",
            'status': "업무 상태",
            'start_date': "시작일",
            'expected_end_date': "종료 예정일",
            'end_date': "종료일",
        }

    def clean(self):
        cleaned_data = super().clean()
        start_date = cleaned_data.get('start_date')
        end_date = cleaned_data.get('end_date')
        expected_end_date = cleaned_data.get('expected_end_date')
        status = cleaned_data.get('status')
        #
        print(status)
        if str(status) == 'Doing':
            self.fields['start_date'].required = True
        elif str(status) == 'Planning':
            self.fields['start_date'].required = False


class IssueForm(forms.ModelForm):
    # end_date = forms.DateField(label="종료일", required=False)

    def __init__(self, *args, **kwargs):
        # first call parent's constructor
        super(IssueForm, self).__init__(*args, **kwargs)
        # there's a `fields` property now
        self.fields['end_date'].required = False
        self.fields['solution'].required = False
        self.fields['replay'].required = False
        self.fields['cause'].required = False

    class Meta:
        model = Issue
        fields = '__all__'

        status_CHOICE = (
            ('분석', '분석'),
            ('해결', '해결'),
            ('보류', '보류'),
            ('공개', '공개'),
        )
        widgets = {
            'work': forms.HiddenInput(attrs={'class': 'form-control col-md-12'}),
            'content': forms.Textarea(attrs={'class': 'form-control', 'rows': '3'}),
            'replay': forms.Textarea(attrs={'class': 'form-control', 'rows': '3'}),
            'cause': forms.Textarea(attrs={'class': 'form-control', 'rows': '3'}),
            'solution': forms.Textarea(attrs={'class': 'form-control', 'rows': '3'}),
            'status': forms.Select(attrs={'class': 'form-control col-md-3'}),
            'start_date': forms.DateInput(attrs={'class': 'form-control col-md-3', 'id':'datepicker1'}),
            'end_date': forms.DateInput(attrs={'class': 'form-control col-md-3', 'id':'datepicker2'}),
        }
        labels = {
            'content': '증상',
            'replay': '재연 경로',
            'cause': "원인 분석",
            'solution': "해결 방안",
            'status': "상태",
            'start_date': "시작일",
            'end_date': "종료일",
        }

main/views.py
from django.contrib.auth.decorators import permission_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.core.exceptions import PermissionDenied
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.views.generic import ListView, CreateView, UpdateView, DetailView, TemplateView
from .models import Work, Issue, WorkStatus, Employee, MyUser
from .forms import WorkForm, IssueForm
from django.views.generic.edit import FormMixin


# Create your views here.
class MainView(LoginRequiredMixin, ListView, FormMixin):
    template_name = 'main/main.html'
    model = Work

    form_class = WorkForm

    def get_context_data(self, **kwargs):
        form = self.form_class()
        context = super().get_context_data(**kwargs)
        context['issues'] = Issue.objects.all()
        context['status'] = WorkStatus.objects.all()
        context['employee'] = Employee.objects.all()
        return context


class SearchView(LoginRequiredMixin, ListView):
    template_name = 'main/main.html'
    model = Work

    def get_queryset(self):
        self.manager = self.kwargs['manager']
        self.status = self.kwargs['status']
        self.contents = self.kwargs['contents']
        if self.contents == "":
            contents = ""

        if self.manager == 'all' and self.status == 'all':
            return Work.objects.filter(work__contains=self.contents)
        elif self.manager == 'all':
            return Work.objects.filter(work__contains=self.contents,
                                       status__title__contains=self.status)
        elif self.status == 'all':
            return Work.objects.filter(work__contains=self.contents,
                                       manager__name__contains=self.manager)
        else:
            return Work.objects.filter(work__contains=self.contents,
                                       manager__name__contains=self.manager,
                                       status__title__contains=self.status)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['issues'] = Issue.objects.all()
        context['status'] = WorkStatus.objects.all()
        context['employee'] = Employee.objects.all()
        if self.manager != 'all':
            context['manager_query'] = self.manager
        if self.status != 'all':
            context['status_query'] = self.status

        return context


class SearchNoConView(LoginRequiredMixin, ListView):
    template_name = 'main/main.html'
    model = Work

    def get_queryset(self):
        self.manager = self.kwargs['manager']
        self.status = self.kwargs['status']

        if self.manager == 'all' and self.status == 'all':
            return Work.objects.all()
        elif self.manager == 'all':
            return Work.objects.filter(status__title__contains=self.status)
        elif self.status == 'all':
            return Work.objects.filter(manager__name__contains=self.manager)
        else:
            return Work.objects.filter(manager__name__contains=self.manager,
                                       status__title__contains=self.status)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['issues'] = Issue.objects.all()
        context['status'] = WorkStatus.objects.all()
        context['employee'] = Employee.objects.all()

        if self.manager != 'all':
            context['manager_query'] = self.manager
        if self.status != 'all':
            context['status_query'] = self.status
        return context


class SearchManView(LoginRequiredMixin, ListView):
    template_name = 'main/main.html'
    model = Work

    def get_queryset(self):
        return Work.objects.filter(manager__name__contains=self.kwargs['query'])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['issues'] = Issue.objects.all()
        context['status'] = WorkStatus.objects.all()
        context['employee'] = Employee.objects.all()
        context['manager_query'] = self.kwargs['query']
        return context


class SearchStatusView(LoginRequiredMixin, ListView):
    template_name = 'main/main.html'
    model = Work

    def get_queryset(self):
        return Work.objects.filter(status__title__contains=self.kwargs['query'])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['issues'] = Issue.objects.all()
        context['status'] = WorkStatus.objects.all()
        context['employee'] = Employee.objects.all()
        context['status_query'] = self.kwargs['query']
        return context


class CreateWorkView(LoginRequiredMixin, CreateView):
    model = Work
    form_class = WorkForm
    template_name = 'main/work_form.html'

    def form_valid(self, form):
        user = get_object_or_404(MyUser, pk=self.request.POST['manager'])
        print(self.request.user)
        if self.request.user != user:
            raise PermissionDenied
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.method == 'GET':
            user = get_object_or_404(MyUser, name=self.request.user)
            form = self.form_class(initial={'manager': user})
            # print(Work.objects.get(pk=self.kwargs['pk']))
            context['form'] = form
            # context['manager'] = MyUser.objects.get(username=self.request.user)

        return context

    def get_success_url(self):
        return reverse('index')


class CreateIssueView(LoginRequiredMixin, CreateView):
    raise_exception = True
    model = Issue
    form_class = IssueForm
    template_name = 'main/issue_form.html'

    def get_success_url(self):
        return reverse('index')

    def form_valid(self, form):
        user = get_object_or_404(MyUser, pk=self.request.POST['manager'])
        if self.request.user != user.name:
            raise PermissionDenied
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.method == 'GET':
            form = self.form_class(initial={'work': Work.objects.get(pk=self.kwargs['work'])})
            # print(Work.objects.get(pk=self.kwargs['pk']))
            context['form'] = form
            context['work'] = Work.objects.get(pk=self.kwargs['work'])

        return context


class UpdateWorkView(PermissionRequiredMixin, UpdateView):
    raise_exception = True
    permission_required = 'main.change_work'
    model = Work
    form_class = WorkForm
    template_name = 'main/work_update_form.html'

    def get_success_url(self):
        return reverse('index')


class UpdateIssueView(PermissionRequiredMixin, UpdateView):
    raise_exception = True
    permission_required = 'main.change_Issue'
    model = Issue
    form_class = IssueForm
    template_name = 'main/issue_update_form.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # print(Issue.objects.get(self.kwargs['pk']))
        context['work'] = Issue.objects.get(pk=self.kwargs['pk']).work
        return context

    def get_success_url(self):
        return reverse('index')


class DetailIssueView(LoginRequiredMixin, DetailView):
    model = Issue
    template_name = 'main/issue_detail.html'


@permission_required('main.delete_work', raise_exception=True)
def delete_work(request, id):
    if request.method == "GET":
        work = Work.objects.get(pk=id)
        work.delete()
        return redirect('/')


@permission_required('main.delete_issue', raise_exception=True)
def delete_issue(request, id):
    if request.method == "GET":
        issue = Issue.objects.get(pk=id)
        issue.delete()
        return redirect('/')

main/templates/main/issue_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>이슈 생성</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
     <script src="https://cdn.jsdelivr.net/npm/gijgo@1.9.10/js/gijgo.min.js" type="text/javascript"></script>
    <link href="https://cdn.jsdelivr.net/npm/gijgo@1.9.10/css/gijgo.min.css" rel="stylesheet" type="text/css" />
</head>
<body>
<div class="row mt-5 justify-content-md-center">
    <h1>이슈 생성</h1>
</div>

<div class="container justify-content-md-center" >
    <form action="." method="post">
        {% csrf_token %}
        <div class="form-group row">
            {{ form.subject.errors }}
            <label for="id_work" class="col-md-2 col-form-label">업무</label>
            <div class="col-md-10">
                {{ form.work }}
                <div class="col-md-10 text-truncate mt-2">
                    {{ work }}
                </div>
{#                <p>{{ form.work }}</p>#}
            </div>
        </div>
        <div class="form-group row">
            {{ form.subject.errors }}
            <label for="id_start_date" class="col-md-2 col-form-label">발생 일자</label>
            <div class="col-md-10">
                {{ form.start_date }}
            </div>
        </div>
        <div class="form-group row">
            {{ form.subject.errors }}
            <label for="id_end_date" class="col-md-2 col-form-label">종료 일자</label>
            <div class="col-md-10">
                {{ form.end_date }}
            </div>
        </div>
        <div class="form-group row">
            {{ form.subject.errors }}
            <label for="id_content" class="col-md-2 col-form-label">증상</label>
            <div class="col-md-10">
                {{ form.content }}
            </div>
        </div>
        <div class="form-group row">
            {{ form.subject.errors }}
            <label for="id_status" class="col-md-2 col-form-label">상태</label>
            <div class="col-md-10">
                {{ form.status }}
            </div>
        </div>
        <div class="form-group row">
            {{ form.subject.errors }}
            <label for="id_replay" class="col-md-2 col-form-label">재연 경로</label>
            <div class="col-md-10">
                {{ form.replay }}
            </div>
        </div>
        <div class="form-group row">
            {{ form.subject.errors }}
            <label for="id_cause" class="col-md-2 col-form-label">원인 분석</label>
            <div class="col-md-10">
                {{ form.cause }}
            </div>
        </div>
        <div class="form-group row">
            {{ form.subject.errors }}
            <label for="id_solution" class="col-md-2 col-form-label">해결 방안</label>
            <div class="col-md-10">
                {{ form.solution }}
            </div>
        </div>
        <button type="button" id="cancel" class="float-left btn btn-danger">취소</button>
        <button type="submit" class="float-right btn btn-primary">확인</button>
    </form>
</div>
</body>
<script type="text/javascript">
    $(function () {
        $('#cancel').click(() => {
            location.href = '/'
        });
        console.log('{{ form.work }}')
    });
    $('#datepicker1').datepicker({
        uiLibrary: 'bootstrap4',
        format: 'yyyy-mm-dd',
    });
    $('#datepicker2').datepicker({
        uiLibrary: 'bootstrap4',
        format: 'yyyy-mm-dd',
    });
</script>
</html>

main/templates/main/issue_update_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>이슈 수정</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/gijgo@1.9.10/js/gijgo.min.js" type="text/javascript"></script>
    <link href="https://cdn.jsdelivr.net/npm/gijgo@1.9.10/css/gijgo.min.css" rel="stylesheet" type="text/css" />
</head>
<body>
<div class="row mt-5 justify-content-md-center">
    <h1>이슈 수정</h1>
</div>

<div class="container justify-content-md-center" >
    <form method="post">
        {% csrf_token %}
        <div class="form-group row">
            {{ form.subject.errors }}
            <label for="id_work" class="col-md-2 col-form-label">업무</label>
            <div class="col-md-10">
                {{ form.work }}
                <div class="col-md-10 text-truncate mt-2">
                    {{ work }}
                </div>
            </div>
        </div>
        <div class="form-group row">
            {{ form.subject.errors }}
            <label for="id_start_date" class="col-md-2 col-form-label">발생 일자</label>
            <div class="col-md-10">
                {{ form.start_date }}
            </div>
        </div>
        <div class="form-group row">
            {{ form.subject.errors }}
            <label for="id_end_date" class="col-md-2 col-form-label">종료 일자</label>
            <div class="col-md-10">
                {{ form.end_date }}
            </div>
        </div>
        <div class="form-group row">
            {{ form.subject.errors }}
            <label for="id_content" class="col-md-2 col-form-label">증상</label>
            <div class="col-md-10">
                {{ form.content }}
            </div>
        </div>
        <div class="form-group row">
            {{ form.subject.errors }}
            <label for="id_status" class="col-md-2 col-form-label">상태</label>
            <div class="col-md-10">
                {{ form.status }}
            </div>
        </div>
        <div class="form-group row">
            {{ form.subject.errors }}
            <label for="id_replay" class="col-md-2 col-form-label">재연 경로</label>
            <div class="col-md-10">
                {{ form.replay }}
            </div>
        </div>
        <div class="form-group row">
            {{ form.subject.errors }}
            <label for="id_cause" class="col-md-2 col-form-label">원인 분석</label>
            <div class="col-md-10">
                {{ form.cause }}
            </div>
        </div>
        <div class="form-group row">
            {{ form.subject.errors }}
            <label for="id_solution" class="col-md-2 col-form-label">해결 방안</label>
            <div class="col-md-10">
                {{ form.solution }}
            </div>
        </div>
        <button type="button" id="cancel" class="float-left btn btn-danger">취소</button>
        <button type="submit" class="float-right btn btn-primary">확인</button>
    </form>
</div>
</body>
<script type="text/javascript">
    $(function () {
        $('#cancel').click(() => {
            location.href = '/'
        })
    });
    $('#datepicker1').datepicker({
        uiLibrary: 'bootstrap4',
        format: 'yyyy-mm-dd',
    });
    $('#datepicker2').datepicker({
        uiLibrary: 'bootstrap4',
        format: 'yyyy-mm-dd',
    });
</script>
</html>

main/templates/main/work_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>업무 생성</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/gijgo@1.9.10/js/gijgo.min.js" type="text/javascript"></script>
    <link href="https://cdn.jsdelivr.net/npm/gijgo@1.9.10/css/gijgo.min.css" rel="stylesheet" type="text/css" />
</head>
<body>
<div class="row mt-5 justify-content-md-center">
    <h1>업무 생성</h1>
</div>

<div class="container justify-content-md-center" >
    <form action="." method="post">
        {% csrf_token %}
        <div class="form-group row">
            <label for="id_manager" class="col-md-2 col-form-label">담당자</label>
            <div class="col-md-10">
                {{ form.manager }}
            </div>
        </div>
        <div class="form-group row">
            <label for="id_supporter" class="col-md-2 col-form-label">업무 협조</label>
            <div class="col-md-10">
                {% for checkbox in form.supporter %}
                    <label class="btn">
                        {{ checkbox.tag }} {{ checkbox.choice_label }}
                    </label>
                {% endfor %}
            </div>
        </div>
        <div class="form-group row">
            <label for="id_work" class="col-md-2 col-form-label">업무 내용</label>
            <div class="col-md-10">
                {{ form.work }}
            </div>
        </div>
        <div class="form-group row">
            <label for="id_status" class="col-md-2 col-form-label">상태</label>
            <div class="col-md-10">
                {{ form.status }}
            </div>
        </div>
        <div class="form-group row">
            <label for="id_start_date" class="col-md-2 col-form-label">시작일</label>
            <div class="col-md-10">
                {{ form.start_date }}
            </div>
        </div>
        <div class="form-group row">
            <label for="id_expected_end_date" class="col-md-2 col-form-label">종료 예정일</label>
            <div class="col-md-10">
                {{ form.expected_end_date }}
            </div>
        </div>
        <div class="form-group row">
            <label for="id_end_date" class="col-md-2 col-form-label">종료일</label>
            <div class="col-md-10">
                {{ form.end_date }}
            </div>
        </div>
        <button type="button" id="cancel" class="float-left btn btn-danger">취소</button>
        <button type="submit" class="float-right btn btn-primary">확인</button>
    </form>
</div>
</body>
<script type="text/javascript">
    $(function () {
        $('#cancel').click(() => {
            location.href = '/'
        });

        $("#datepicker1").attr("required", false);
        $("#datepicker2").attr("required", true);
        $("#datepicker3").attr("required", false);

        $('#id_status').change(function () {
            if ($("#id_status option:selected").text() === "Doing") {
                $("#datepicker1").attr("required", true);
                $("#datepicker2").attr("required", true);
                $("#datepicker3").attr("required", false);
            }
            if ($("#id_status option:selected").text() === "Planning") {
                $("#datepicker1").attr("required", false);
                $("#datepicker2").attr("required", true);
                $("#datepicker3").attr("required", false);
            }
            if ($("#id_status option:selected").text() === "Done") {
                $("#datepicker1").attr("required", true);
                $("#datepicker2").attr("required", true);
                $("#datepicker3").attr("required", true);
            }
            if ($("#id_status option:selected").text() === "Holding") {
                $("#datepicker1").attr("required", false);
                $("#datepicker2").attr("required", false);
                $("#datepicker3").attr("required", false);
            }
            if ($("#id_status option:selected").text() === "Delay") {
                $("#datepicker1").attr("required", true);
                $("#datepicker2").attr("required", true);
                $("#datepicker3").attr("required", false);
            }
            if ($("#id_status option:selected").text() === "Expired") {
                $("#datepicker1").attr("required", false);
                $("#datepicker2").attr("required", false);
                $("#datepicker3").attr("required", false);
            }
        });

    })
</script>
<script>
        $('#datepicker1').datepicker({
            uiLibrary: 'bootstrap4',
            format: 'yyyy-mm-dd',
            value: "{{ form.start_date.value|date:"Y-m-d" }}"
        });
        $('#datepicker2').datepicker({
            uiLibrary: 'bootstrap4',
            format: 'yyyy-mm-dd',
        });
        $('#datepicker3').datepicker({
            uiLibrary: 'bootstrap4',
            format: 'yyyy-mm-dd',
        });
</script>
</html>